language: python
python:
  - "3.8"
install:
  - pip install -r requirements/install.txt
  - pip install -r requirements/test.txt
  - pip install -r requirements/ci.txt
script:
  - make test-cov
after_success:
  - codecov
